### ISSUE TITLE
Migaku settings layout on Mac

### ISSUE THREAD

**Issue by GriefBacon** [MikeMoolenaar/Migaku-Japanese-Addon-Updated#3]
**Environment**
  - OS: [ MacOS - Ventura 13.2]
  - Anki version: [ 2.1.60 ]

**Description**  
[ The area where you set the color code for pitch accent is squished on the top row. It also looks like the 'restore defaults' button is clipped on the edges, too.

I have tried changing the size of the window and the result stays the same.]
<img width="1196" alt="Screenshot 2023-03-08 at 8 48 52" src="https://user-images.githubusercontent.com/80210160/223581959-26a2bdf0-4444-467f-94b4-70c580ea376a.png">

**Comment by MikeMoolenaar** [comment]
Hi, seems like this only occurs on Anki 2.1.60, having  the same issue on Linux. I'll do a release this weekend to fix the layout bugs and clean it up a bit more.

**Comment by GriefBacon** [comment]
Yep, that fixed it.

Thank you for the quick update! :D
