### ISSUE TITLE
coloured kanji not showing up

### ISSUE THREAD

**Issue by j0yyyyy** [MikeMoolenaar/Migaku-Japanese-Addon-Updated#4]
**Environment**
  - OS: [ Windows 10 ]
  - Anki version: [ 2.1.66 ]

**Description**  
I've installed the addon, I can see the Migaku tab with the settings, but when I open my cards it just shows as the syntax rather than the coloured pitch accent. I'm not sure if this is a bug, or if I did something wrong, so I hope it's alright that I'm posting this here.

![troubleshoot](https://github.com/MikeMoolenaar/Migaku-Japanese-Addon-Updated/assets/145853814/56074330-6001-4db4-8ffb-a7e7e693d8a6)

**Comment by MikeMoolenaar** [comment]
Yes it's alright to post here! Did you configure the card field in Migaku > Japanese settings > Active Fields? It's configured to work with the migaku note type by default, but if you have a custom note type you need to configure it there.

For example, mine looks like this
![2023-09-24_10-03.png](https://github.com/MikeMoolenaar/Migaku-Japanese-Addon-Updated/assets/20370521/e65f301c-644a-4bf5-930c-7c9095e74834)

**Comment by j0yyyyy** [comment]
oh yea that was it haha! Since there was already a bunch of fields set by default I thought it had saved my fields from before (I had even saved a screenshot of all my settings beforehand but didn't think to double-check...) 
Anyway thanks for the help and for making the addon usable on recent anki versions that was a life-saver! (now to wait until someone does the same for morphman haha...)

**Comment by MikeMoolenaar** [comment]
Glad I could help! Best of luck with your studies.
