### ISSUE TITLE
generation of sound creates "--IND--" around word

### ISSUE THREAD

**Issue by limarman** [MikeMoolenaar/Migaku-Japanese-Addon-Updated#8]
**Environment**
  - OS: Windows 11
  - Anki version:⁨ 24.06.3 (d678e393)⁩

Hi,

first I want to thank you that you kept this addon alive. I think this is the best free add-on out there for Japanese sentence cards.

It seems to work very well for newer versions, but I have one specific problem when generating the accent / audio for a particular word with the shortcut f2. Around the word there appears "--IND--" "--IND--". I have looked into the code and it seems like this is done on purpose, I guess to mark the word in the sentence for further processing. However after generating the audio it is not cleaned again.

This is how it looks after I have generated the audio.
![grafik](https://github.com/user-attachments/assets/5ac2814b-58ba-4d33-a9c2-b06080d83e0f)

Do you know why this happens and how it can be fixed?

Help is greatly appreciated!!

Best,
Ramil

**Comment by MikeMoolenaar** [comment]
Hi, I can also reproduce this issue with the Generate Word (F3) button, is it correct that you also have the problem with this button? I personally only use the Generate Sentence button and the problem seems to not be there.  

I'll look into it once I have a bit more time on my hands.

**Comment by MikeMoolenaar** [comment]
Yeah I can't reproduce it with the sentence button (f2), could you also share a screenshot of the Migaku Settings screen (only the first screen "options" is fine for now).

**Comment by limarman** [comment]
Hi,

yeah I also do not have any problems with the sentence button (F2), it is only the pitch/audio generating button (F3) that creates this issue.

Here the screenshot of the settings (I have not changed them since installation, so they should be default.)
![grafik](https://github.com/user-attachments/assets/d49357cb-2771-4e9f-b508-de4e1e169695)

Thanks for the help!

**Comment by MikeMoolenaar** [comment]
@limarman I believe I found the issue and made a release. Could you test if this fixes the problem? Please download the zip file and extract to the Anki plugin folder overwriting all files.

https://github.com/MikeMoolenaar/Migaku-Japanese-Addon-Updated/releases/tag/V1.2.3%2B1.0.2

**Comment by limarman** [comment]
@MikeMoolenaar I tried it out, it works great! Thank you so much !! :)

**Comment by MikeMoolenaar** [comment]
> @MikeMoolenaar I tried it out, it works great! Thank you so much !! :)

Great to hear
